name: Region Params

on:
  push:
    paths:
      - "region_params/**"
      - ".github/workflows/region_params.yml"
    # tags:
    #   - "*-region_params"
  pull_request:
    branches:
      - master
    paths:
      - "region_params/**"
      - ".github/workflows/region_params.yml"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Build | Matrix
        id: set-matrix
        run: echo "matrix=$(find region_params -name '*.json' -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [build-matrix]
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Tools
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        env:
          ## Allow install into PATH
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: helium/lorawan-h3
          tag: lw-generator-v0.2.1-rc.1

      - name: Build | Generate
        run: |
          lw-generator params generate ${{ matrix.region }}.json ${{ matrix.region }}.rpz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Release | Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          name: region_params
          files: |
            "*.rpz"
