name: Region Maps

on:
  push:
    paths:
      - "regions.txt"
      - "extern/hplans/**"
      - ".github/workflows/region_maps.yml"
  pull_request:
    branches:
      - master
    paths:
      - "regions.txt"
      - "extern/hplans/**"
      - ".github/workflows/region_maps.yml"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Build | Matrix
        id: set-matrix
        run: echo "matrix=$(cat regions.txt| jq -R -s -c 'split("\n")')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [build-matrix]
    strategy:
      matrix:
        region: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup | Tools
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: helium/lorawan-h3
          tag: lw-generator-v0.4.0

      - name: Build | Generate
        env:
          RESOLUTION: 7
        run: |
          lw-generator regions generate extern/hplans/${{ matrix.region }}.geojson ${{ matrix.region }}.res${{ env.RESOLUTION }}.h3idz --resolution ${{ env.RESOLUTION }}

      - name: Release | Artifacts
        if: startsWith(github.ref, 'refs/tags/region_maps')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          name: ${{github.ref_name}}
          files: |
            *.h3idz
