name: Tools

on:
  push:
    ignore-paths:
      - "extern/**"
      - "region_params/**"
      - "README.md"
  pull_request:
    branches:
      - master
    ignore-paths:
      - "extern/**"
      - "region_params/**"
      - "README.md"

jobs:
  hygiene:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup | Protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Hygiene
        run: |
          cargo fmt  -- --check
          cargo clippy --all-features --locked -- -D clippy::all

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup | Protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Release
        run: |
          cargo build --all --release --locked

      - name: Release | Prepare
        run: |
          tar -zcv -C target/release -f lw-generator.tar.gz lw-generator
          sha256sum -b --tag lw-generator.tar.gz > lw-generator.checksum

      - name: Release | Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            lw-generator.tar.gz
            lw-generator.checksum
